@ToDo_HostAddress = http://localhost:5001

GET {{ToDo_HostAddress}}/api/todo
Content-Type: application/json

###

GET {{ToDo_HostAddress}}/api/todo/1
Content-Type: application/json

###

POST {{ToDo_HostAddress}}/api/todo/add
Content-Type: application/json

{
  "title": "http",
  "description": "daf"
}

###

PUT {{ToDo_HostAddress}}/api/todo/5
Content-Type: application/json

{
  "title": "http",
  "description": "daf"
}

###

DELETE {{ToDo_HostAddress}}/api/todo/a29466ac-d632-464b-a385-fbfbb536fc89
Content-Type: application/json

###

DELETE {{ToDo_HostAddress}}/api/todo/
Content-Type: application/json